version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: sdecandelario/php-composer:7.1
        volumes:
            - .:/app
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
            - ./php.ini-development:/usr/local/etc/php/php.ini
        working_dir: /app
        networks:
            - code-network
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ddd-example-host
            MYSQL_USER: silex
            MYSQL_PASSWORD: silex
networks:
    code-network:
        driver: bridge