version: '2'

services:
    nginx:
        image: nginx:latest
        container_name: ddd_example_nginx
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./etc/infraestructure/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        volumes_from:
            - php

    php:
        image: jorge07/alpine-php:7-dev
        container_name: ddd_example_php
        ports:
            - "2244:22"
            - "9000:9000"
        volumes:
            - "$PWD:/app"
        environment:
            - PHP_IDE_CONFIG=serverName=SomeName
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: ddd_example_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ddd-example
            MYSQL_USER: silex
            MYSQL_PASSWORD: silex