version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./etc/infraestructure/nginx/site.conf:/etc/nginx/conf.d/default.conf

    php:
        image: sdecandelario/php-composer:7.1
        volumes:
            - .:/app
            - ./etc/infraestructure/php/php.ini-development:/usr/local/etc/php/php.ini
        working_dir: /app

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ddd-example
            MYSQL_USER: silex
            MYSQL_PASSWORD: silex