version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/ddd-example-host
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - .:/ddd-example-host
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network
    composer:
        restart: 'no'
        image: composer/composer:php7
        command: install
        volumes:
            - .:/ddd-example-host

networks:
    code-network:
        driver: bridge