TodoList\Domain\Model\Item\Item:
    type: entity
    table: items
    id:
        id:
            type: item_id
            column: id
            length: 36
    fields:
        title:
            type: string
            length: 255